# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ratelimit.v1 import ratelimit_pb2 as ratelimit_dot_v1_dot_ratelimit__pb2


class RateLimiterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsAllowed = channel.unary_unary(
                '/ratelimit.v1.RateLimiterService/IsAllowed',
                request_serializer=ratelimit_dot_v1_dot_ratelimit__pb2.IsAllowedRequest.SerializeToString,
                response_deserializer=ratelimit_dot_v1_dot_ratelimit__pb2.IsAllowedResponse.FromString,
                _registered_method=True)


class RateLimiterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IsAllowed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateLimiterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsAllowed': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAllowed,
                    request_deserializer=ratelimit_dot_v1_dot_ratelimit__pb2.IsAllowedRequest.FromString,
                    response_serializer=ratelimit_dot_v1_dot_ratelimit__pb2.IsAllowedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratelimit.v1.RateLimiterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratelimit.v1.RateLimiterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RateLimiterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IsAllowed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratelimit.v1.RateLimiterService/IsAllowed',
            ratelimit_dot_v1_dot_ratelimit__pb2.IsAllowedRequest.SerializeToString,
            ratelimit_dot_v1_dot_ratelimit__pb2.IsAllowedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
