# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ratelimit/v1/ratelimit.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'ratelimit/v1/ratelimit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cratelimit/v1/ratelimit.proto\x12\x0cratelimit.v1\"\xa9\x01\n\x10IsAllowedRequest\x12\"\n\naccess_key\x18\x01 \x01(\tH\x00R\taccessKey\x88\x01\x01\x12\x15\n\x06ip_key\x18\x02 \x01(\tR\x05ipKey\x12\x19\n\x05limit\x18\x03 \x01(\x05H\x01R\x05limit\x88\x01\x01\x12\x1b\n\x06window\x18\x04 \x01(\x05H\x02R\x06window\x88\x01\x01\x42\r\n\x0b_access_keyB\x08\n\x06_limitB\t\n\x07_window\"\xaf\x01\n\x11IsAllowedResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12#\n\rcurrent_count\x18\x02 \x01(\x05R\x0c\x63urrentCount\x12\x14\n\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1c\n\tremaining\x18\x04 \x01(\x05R\tremaining\x12\x1d\n\x07message\x18\x05 \x01(\tH\x00R\x07message\x88\x01\x01\x42\n\n\x08_message2b\n\x12RateLimiterService\x12L\n\tIsAllowed\x12\x1e.ratelimit.v1.IsAllowedRequest\x1a\x1f.ratelimit.v1.IsAllowedResponseB1Z/headsntails-core/proto/ratelimit/v1;ratelimitv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ratelimit.v1.ratelimit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/headsntails-core/proto/ratelimit/v1;ratelimitv1'
  _globals['_ISALLOWEDREQUEST']._serialized_start=47
  _globals['_ISALLOWEDREQUEST']._serialized_end=216
  _globals['_ISALLOWEDRESPONSE']._serialized_start=219
  _globals['_ISALLOWEDRESPONSE']._serialized_end=394
  _globals['_RATELIMITERSERVICE']._serialized_start=396
  _globals['_RATELIMITERSERVICE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
